name: Starter CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  ci:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Use Node.js 22.x
      uses: actions/setup-node@v4
      with:
        node-version: '22.x'
        cache: 'npm'
    - name: Delete prepare script
      run: npm pkg delete scripts.prepare
    - name: Install dependencies
      run: npm install --frozen-lockfile
    - name: Linting
      run: npm run lint:ci
    - name: Type Checking
      run: npm run type-check
    - name: Tests
      run: npm run test:ci
